apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-istio-proxy
  name: redis-istio-proxy
  namespace: db
spec:
  containers:
  - image: refis
    name: redis-istio-proxy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
