apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: demo-postgres
  namespace: demo-db
spec:
  parentRefs:
    - name: postgres-gateway
      namespace: default
      sectionName: postgres-tls
  hostnames:
    - demo-pg.db.infrasnow.com
  rules:
    - backendRefs:
        - name: demo-postgres
          port: 5432
