Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"   # more stable than ubuntu/jammy64
  config.vm.hostname = "lvm-lab"
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = "lvm-lab-#{Time.now.to_i}"

    # Create & attach extra disks
    (1..3).each do |i|
      disk_file = "./disk_#{i}.vdi"

      unless File.exist?(disk_file)
        vb.customize ["createmedium", "disk",
                      "--filename", disk_file,
                      "--size", 5 * 1024]
      end

      vb.customize ["storageattach", :id,
                    "--storagectl", "SATA Controller",
                    "--port", i+1,      # port 0 is already used by root disk
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", disk_file]
    end
  end

  config.vm.synced_folder ".", "/vagrant"
end