apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subscriber-pvc
  namespace: demo
spec:
  storageClassName: topolvm-provisioner-thin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-subscriber
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-subscriber
  template:
    metadata:
      labels:
        app: pg-subscriber
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: testdb
          args:
            - "-c"
            - "listen_addresses=*"
          volumeMounts:
            - name: subscriber-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: subscriber-storage
          persistentVolumeClaim:
            claimName: subscriber-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-subscriber
  namespace: demo
spec:
  selector:
    app: pg-subscriber
  ports:
    - port: 5432
      targetPort: 5432