apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: csi-s3-manual-pvc-backup
  namespace: csi-s3
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: csi-s3-manual-pvc
    namespace: csi-s3
  backends:
    - name: s3-storage
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit:
      scheduler:
        schedule: "*/5 * * * *"
        suspend: true
#        jobTemplate:
#          template:
#            spec:
#              resources:
#                requests:
#                  cpu: 2000m
#                  memory: 2000Mi
      repositories:
        - name: pvc-backup
          backend: s3-storage
          directory: /pvc-backup
          encryptionSecret:
            name: encrypt-secret
            namespace: demo
          deletionPolicy: Retain
      addon:
        name: pvc-addon
        tasks:
          - name: logical-backup
            # params:
            #   exclude: /kubestash-data/lost+found
        jobTemplate:
          spec:
            resources:
              requests:
                cpu: "4"
                memory: "8Gi"
              limits:
                cpu: "4"
                memory: "8Gi"