apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example
spec:
  containers:
    - name: example-container
      image: nginx:latest
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
        limits:
          cpu: "1"
          memory: "4Gi"

