apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: demo
spec:
  storageClassName: csi-gce-pd-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
