apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  namespace: demo

spec:
  containers:
    - name: pause
      image: ubuntu:22.04
      command:
        - bash
        - -c
        - |
          sleep infinity
      volumeMounts:
        - mountPath: /data
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: restore-pvc