apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-backup-config
  namespace: topolvm-system
data:
  repositoryURL: "s3:s3.amazonaws.com/topolvm-snapshots/online-snapshots/"
  backupFlags: |
    --exclude /tmp
    --cleanup-cache
  restoreFlags: |
    --cleanup-cache
  globalFlags: |
    --no-lock
    --limit-upload=4
    --verbose
  providerOptions: |
    s3.region=us-east-1
    s3.bucket-lookup=auto
    s3.storage-class=STANDARD_IA
    s3.enable-restore=true
    s3.restore-days=14
    s3.restore-tier=Bulk
    s3.restore-timeout=12h
    s3.retries=5
  storageSecretRef: "aws-credentials"
